sample_sheet: "/data/Ajinkya/MILK_AMR/MILK-Isolates/Round09_Milk_AMR_09042025/Round09_Milk_AMR_09042025/20250409_1936_P2S-02808-B_PBC50427_9c20e26b/Analysis/Bac-AMR/sample.csv"     # CSV with columns: barcode,sample_id
raw_dir:      "/data/Ajinkya/MILK_AMR/MILK-Isolates/Round09_Milk_AMR_09042025/Round09_Milk_AMR_09042025/20250409_1936_P2S-02808-B_PBC50427_9c20e26b/Analysis/Test"           # dir of per-barcode FASTQ/FASTQ.GZ
threads:      16
quality:      10
min_length:   1000
assembler:    "flye"            # or "canu"
genome_size:  "5m"              # for canu
medaka_model: "r941_prom_sup_g507"
# full absolute path to the directory where your MOB-Suite DBs live
mob_db_dir:  "/data/Ajinkya/miniconda3/envs/mobsuite/lib/python3.11/site-packages/mob_suite/databases/"

